services:
  app:
    image: node:23
    container_name: dev-planner-bot
    # restart: unless-stopped

    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run server"